website/config/routes.rb
Rails.application.routes.draw do
 
  get 'cart/checkout'

  get 'products/checkout'

  get 'product/checkout'

  get 'cart/index'

  resources :profiles

  devise_for :users
  
  get 'homepage/store'

  get 'homepage/aboutUs'

  get 'homepage/contactUs'

  get 'homepage/index'
  
  get 'products/index'
  
  get 'users/sign_up'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  
  get '/homepage' => 'homepage#index'
  
  resources :products

    root 'homepage#index'

end

website/app/models/product.rb
class Product < ActiveRecord::Base
  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end
end

website/app/models/profile.rb
class Profile < ActiveRecord::Base
  
  belongs_to :user
  
  def self.search(search)
    where("firstName LIKE ?", "%#{search}%")
  end
  
end

website/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
end

website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  
  protect_from_forgery with: :exception
  
  #def after_sign_in_path_for(resource)
  #  "/signedinuserprofile"
  #end
  
end

website/app/controllers/cart_controller.rb
class CartController < ApplicationController

  before_filter :authenticate_user!
  
  def add
    # get the ID of the product
    id = params[:id]
    
    #if the cart is already been created, use the existing cart
    #else create a blank cart
    if session[:cart] then
      cart = session[:cart]
    else
      session[:cart] = {}
      cart = session[:cart]
    end
      
      #if the product has already been added to the cart, increment the value
      #else set the value to 1
    if cart[id] then
      cart[id] = cart[id] + 1
    else
      cart[id] = 1
    end 
      
      #redirect to the cart display page
      redirect_to :action => :index
    end
      
      def clearCart
        #set the session variable to nil and redirect
       session[:cart] = nil
        redirect_to :action => :index
      end
      
      def index 
        # if there is a cart, pass it to the page for display
        # else pass an empty value
        if session[:cart] then
          @cart = session[:cart]
        else
          @cart = {}
        end    
      end
end

website/app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

website/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :ensure_admin, :only => [:edit, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # Callback
  before_action :store_user_location!, if: :storable_location?


  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    if params[:search]
      @products = Product.search(params[:search]).order("created_at ASC")
    else
      @products = Product.all.order("created_at ASC")
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def ensure_admin
       unless current_user && current_user.admin?
         render :text => "Access Error Message", :status => :unauthorized
       end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:image, :name, :description, :price, :quantity, :category)
    end

    def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr? 
    end

    def store_user_location!
      store_location_for(:user, request.fullpath)
    end
  
  end

website/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_filter :authenticate_user!
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @profiles = Profile.all
    respond_with(@profiles)
    if params[:search]
      @profiles = Profile.search(params[:search]).order("created_at ASC")
    else
      @profiles = Profile.all.order("created_at ASC")
    end
  end

  def show
    respond_with(@profile)
  end

  def new
    @profile = Profile.new
    @profile.user_id = current_user.id
    respond_to do |format|
       format.html # new.html.erb
       format.json { render json: @profile }
    end
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.save
    respond_with(@profile)
  end

  def update
    @profile.update(profile_params)
    respond_with(@profile)
  end

  def destroy
    @profile.destroy
    respond_with(@profile)
  end
  
#   def signedinuserprofile
#     profile = Profile.find_by_user_id(current_user.id)
#      if profile.nil?
#        redirect_to "/profiles/new"
#      else
#        @profile = Profile.find_by_user_id(current_user.id)
#        redirect_to "/profiles/#{@profile.id}"
#      end
#   end
  
  def ensure_admin
       unless current_user && current_user.admin?
         render :text => "Access Error Message", :status => :unauthorized
       end
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:firstName, :lastName, :address, :phone, :user_id)
    end
 
end

website/app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  # Callback
  before_action :store_user_location!, if: :storable_location?

  before_action :authenticate_user!
  
   #after_sign_in_path_for is called by devise
   # def after_sign_in_path_for(user)
   #    "/signedinuserprofile"    #provide the path for user's profile
   # end
  
   private

    def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr? 
    end

    def store_user_location!
      store_location_for(:user, request.fullpath)
    end
end

website/app/helpers/application_helper.rb
module ApplicationHelper
end

website/app/helpers/cart_helper.rb
module CartHelper
end

website/app/helpers/homepage_helper.rb
module HomepageHelper
end

website/app/helpers/product_helper.rb
module ProductHelper
end

website/app/helpers/products_helper.rb
module ProductsHelper
end

website/app/helpers/profiles_helper.rb
module ProfilesHelper
end

website/app/helpers/sessions_helper.rb
module SessionsHelper
end

website/app/views/cart/checkout.html.erb
<p>Order submitted!</p>
<p>Thanks for buying with us!</p>

website/app/views/cart/index.html.erb
<html>
  <head></head>
  <body>
    <div class="title">
       <h1>Your Cart</h1>
    </div>
    <div class="title">
      <% if @cart.empty? %>
      <p style = "color:red;">Cart is empty</p>
      <% end %>
    </div>

 <% total = 0 %>

 <table class="cart_table">
  <thead>
    <tr>
      <th>Item</th>
      <th>Price</th>
      <th>Qty</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
      <% @cart.each do |id,quantity | %>
        <% product = Product.find_by_id(id) %>
        <tr>
          <td><%= link_to product.name, product %></td>
          <td><%= number_to_currency(product.price) %></td>
          <td><%= quantity %><br /></td>
          <td><%= number_to_currency(quantity * product.price, :unit => "€ ") %></td>
        </tr>
        <% total += quantity * product.price %>
        <% end %>

        <tr>
          <td colspan="4">
            <div>Total:</div>
          </td>
          <td>
            <div><%= number_to_currency(total, :unit => "€ ") %></div>
          </td>
        </tr>
    </tbody>
 </table>
    <div class="bottom-links">
      <%= link_to 'Continue Shopping', :controller => :products %></br></br>
      <% if ! @cart.empty? %>
      <%= link_to 'Confirm and checkout', cart_checkout_path %>
      <% end %>
    </div>
  </body>
</html>

website/app/views/homepage/aboutUs.html.erb
<h1>Homepage#aboutUs</h1>
<p>Find me in app/views/homepage/aboutUs.html.erb</p>

website/app/views/homepage/contactUs.html.erb
<h1>Homepage#contactUs</h1>
<p>Find me in app/views/homepage/contactUs.html.erb</p>

website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => "true" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => "true" %>
      <%= csrf_meta_tags %>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Bikes for you is a premium store for purchasing bikes and bike related accessories">

        <link rel="stylesheet" type="text/css" href="/assets/normalize.css">
        <link rel="stylesheet" type="text/css" href="/assets/grid.css">
        <!--link rel="stylesheet" type="text/css" href="/assets/ionicons.min.css"-->
        <link rel="stylesheet" type="text/css" href="/assets/animate.css">
        <link rel="stylesheet" type="text/css" href="/assets/style.css">
        <link rel="stylesheet" type="text/css" href="/assets/queries.css">
        <link href='https://fonts.googleapis.com/css?family=Lato:100,300,400,300italic' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <title>B4U</title>
        <style>
          @import url('https://fonts.googleapis.com/css?family=Covered+By+Your+Grace');
        </style>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.5/waypoints.min.js"></script>
    </head>

<body>
  <p class="notice">
    <%= notice %>
  </p>
  <p class="alert">
    <%= alert %>
  </p>
  <%= yield %>

</body>


</html>

website/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form_edit_product">
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

website/app/views/products/edit.html.erb
<div class="title">
<h1>Editing product</h1>
</div>
<%= render 'form' %>

<div class=bottom-links>
<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
</div>

website/app/views/products/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head> </head>

<body>
  <header>
    <nav>
      <div class="row">
        <img src="/assets/logo.png" alt="logo" class="logo">
        <img src="/assets/logo1.png" alt="logo1" class="logo1">

        <div class="user_session">
          <ul>
            <% if user_signed_in? %>
               <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
               <li><%= link_to('Profile', profiles_path) %></li>
            <% else %>
               <li><%= link_to('Login', user_session_path) %></li>
            <% end %>
            <li>
              <% if user_signed_in? %>
                <%= current_user.email %>
              <% end %>
            </li>
          </ul>
        </div>
        <ul class="main-nav-1 js--main-nav">
          <li><a href="/cart"> <i class="material-icons">shopping_cart</i></a></li>
          <li><a href="/homepage">Home</a></li>
          <li><a href="#shop_now">BUY NOW</a></li>
         </ul>
      </div>
    </nav>

    <div class="hero-text-box">
      <h1>Welcome to B4U Shop</h1>
      <h1>Find our products bellow :)</h1>
    </div>

  
  </header>

  <section class="section-features js--section-features" id="shop_now">
    <div class="search">
      <%= form_tag(products_path, :method => "get", id: "search_form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Products" %>
      <%= submit_tag "Search" %>
      <% end %>
    </div>
    <div class="col">
      <table class="products_table">
        <thead>
          <tr>
            <th>Preview</th>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Category</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td>
                <%= link_to (image_tag product.image, :style => "height:100px"), product %>
              </td>
              <td>
                <%= product.name %>
              </td>
              <td>
                <%= product.description %>
              </td>
              <td>
                <%= product.price %>
              </td>
              <td>
                <%= product.quantity %>
              </td>
              <td>
                <%= product.category %>
              </td>
              <td>
                <%= link_to 'Show', product %>
              </td>
              <td><a href="/cart/<%= product.id %>">Buy</a></td>
              <% if current_user && current_user.admin? %>
                <td>
                  <%= link_to 'Edit', edit_product_path(product) %>
                </td>
                <td>
                  <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
               <% end %>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
    <div class="bottom-links">
      <ul>
        <li>
          <% if current_user && current_user.admin? %>
            <%= link_to 'New Product', new_product_path %>
              <% end %>
        </li>         
      </ul>
    </div>
  </section>
</body>
</html>

website/app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

website/app/views/products/show.html.erb
<html>
  <head></head>
  <body>
    <div class="title">
       <h1>Showing Product</h1>
    </div>

    <table class="products_table">
    <thead>
      <tr>
        <th>Preview</th>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Category</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= link_to (image_tag @product.image, :style => "height:100px"), @product %></td>
        <td><%= @product.name%></td>
        <td><%= @product.description %></td>
        <td><%= @product.price %></td>
        <td><%= @product.category %></td>
      </tr>
    </tbody>
   </table>
  </body>
  <div class="bottom-links">
  <% if current_user && current_user.admin?%>
     <%= link_to 'Edit', edit_product_path(@product) %> |
    <% else %>
    <%= link_to 'Back', products_path %> |
    <%= link_to 'Home', root_path %>
    <% end %>
  </div>
</html>

website/app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<section class="form_edit_profile">
  <div class="field">
    <%= f.label :firstName %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </section>
<% end %>

website/app/views/profiles/edit.html.erb
<div class="title">
  <h1>Editing Profile</h1>
</div>

<%= render 'form' %>

<div class="bottom-links">
  <%= link_to 'Show', @profile %> |
  <%= link_to 'Back', profiles_path %>
</div>

website/app/views/profiles/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head> </head>

<body>
  <header>
    <nav>
      <div class="row">
        <img src="/assets/logo.png" alt="logo" class="logo">
        <img src="/assets/logo1.png" alt="logo1" class="logo1">

        <div class="user_session">
          <ul>
            <% if user_signed_in? %>
               <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
               <li><%= link_to('Profile', profiles_path) %></li>
            <% else %>
               <li><%= link_to('Login', user_session_path) %></li>
            <% end %>
            <li>
              <% if user_signed_in? %>
                <%= current_user.email %>
              <% end %>
            </li>
          </ul>
          <ul class="main-nav-1 js--main-nav">
          <li><a href="/cart"> <i class="material-icons">shopping_cart</i></a></li>
          <li><a href="/homepage">Home</a></li>
          <li><a href="#profiles">SHOW PROFILES</a></li>
        </ul>
        </div>
          </div>
    </nav>

    <div class="hero-text-box">
      <h1>Managing Profiles</h1>
    </div>

  </header>

  <section class="col span-1-of-3 js--section-features" id="profiles">
    <div class="search">
      <%= form_tag(profiles_path, :method => "get", id: "search_form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Profile" %>
      <%= submit_tag "Search" %>
      <% end %>
    </div>
  <div class="col">
      <table class="profiles_table">
        <thead>
          <tr>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Address</th>
            <th>Phone</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @profiles.each do |profile| %>
            <tr>
              <td><%= profile.firstName %></td>
              <td><%= profile.lastName %></td>
              <td><%= profile.address %></td>
              <td><%= profile.phone %></td>
              <td><%= link_to 'Show', profile %></td>
              <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
              <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        </tbody>
      </table>  
  </div>
  <div>  
    <% if current_user.admin? %>
        <%= link_to 'New Profile', new_profile_path %>
    <% end %>
  </div>
      
<% end %>

website/app/views/profiles/new.html.erb
<h1>New profile</h1>
<div class="signup">
<h2>New profile </h2>
</div>

<div class="col span-1-of-3">
<%= render 'form' %>

<%= link_to 'Back', profiles_path %>
</div>

website/app/views/profiles/show.html.erb
<html>
  <head></head>
  <body>
    <div class="signup">
       <h2>Showing Profile</h2>
    </div>

    <table class="users_table">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Last name</th>
        <th>Address</th>
        <th>Phone</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= @profile.firstName %></td>
        <td><%= @profile.lastName %></td>
        <td><%= @profile.address %></td>
        <td><%= @profile.phone %></td>
      </tr>
      </tbody>
    </table>
  </body>
  <div class="bottom-links">
    <%= link_to 'Edit', edit_profile_path(@profile) %> |
    <%= link_to 'Back', profiles_path %> |
    <%= link_to 'Home', root_path %> |
    <%= link_to 'Shop', products_path %>
  </div>
</html>

website/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br /><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br /><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br /><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br /><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br /><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br /><br />
  <% end -%>
<% end -%>